// Type declarations for @itslil/lil2-remark-math. Generated by lilscript-work/lil2/release/types.mjs.
/**
 * mdast as positional columns: the parser's own arrays, indexed by node id. Node 0 is the root.
 *
 * A node's kind is `kind[node]`, one of the `K_*` constants (`/constants`). Its children run from
 * `firstChild[node]` along `nextSibling`; -1 ends the list and means "none" in every link column.
 * Positions are offsets into the source; `lineStarts` turns an offset into a line and column.
 *
 * Strings per kind (`s1` / `s2` / `s3`): text, html, inlineCode, math, inlineMath: value; code: value / lang /
 * meta; definition and link: url / title; image: url / title / alt; imageReference: alt. `flags` (`N_*` bits)
 * says which optional ones are set. `num` is a heading's depth, a list's start, a reference's type (0 shortcut,
 * 1 collapsed, 2 full) or, for a table, the offset of its alignments in `aux` (a count, then one `ALIGN_*` per
 * column). `identifier[node]` is an id into `identifiers` (-1: none).
 */
export type MdastColumns = readonly [
  kind: readonly number[],
  flags: readonly number[],
  parent: readonly number[],
  firstChild: readonly number[],
  nextSibling: readonly number[],
  startOffset: readonly number[],
  endOffset: readonly number[],
  num: readonly number[],
  s1: readonly string[],
  s2: readonly string[],
  s3: readonly string[],
  identifier: readonly number[],
  label: readonly string[],
  lineStarts: readonly number[],
  identifiers: readonly string[],
  aux: readonly number[],
]

/**
 * hast as positional columns: the transformer's own arrays, indexed by node id; `root` is the root's id.
 *
 * A node's kind is `kind[node]`, one of the `H_*` constants (`/constants`); an element's tag
 * name is `tagNames[tag[node]]` and text, comment and raw nodes keep their text in `value`. Children run from
 * `firstChild[node]` along `nextSibling`; -1 ends the list and means "none" in every link column. An element's
 * properties run from `propHead[node]` along `propNext`: each has a name (`propNames[propName[p]]`), a kind
 * (`P_*`: string, number, boolean, list, keyword or float) and its value in `propString` (string and list
 * values; a list is space separated) or `propNumber` (numbers, booleans as 0/1, and `P_KEYWORD` ids into
 * `keywordNames`). Positions are offsets into the source; `lineStarts` turns an offset into a line and column.
 */
export type HastColumns = readonly [
  root: number,
  kind: readonly number[],
  parent: readonly number[],
  firstChild: readonly number[],
  nextSibling: readonly number[],
  tag: readonly number[],
  value: readonly string[],
  startOffset: readonly number[],
  endOffset: readonly number[],
  flags: readonly number[],
  meta: readonly string[],
  propHead: readonly number[],
  propName: readonly number[],
  propKind: readonly number[],
  propString: readonly string[],
  propNumber: readonly number[],
  propNext: readonly number[],
  lineStarts: readonly number[],
  tagNames: readonly string[],
]

/** Property names by id (`propName` values index it). */
export declare const propNames: readonly string[]
/** Keyword values by id (a `P_KEYWORD` property's `propNumber` indexes it). */
export declare const keywordNames: readonly string[]

/**
 * Parses markdown with math (`$$` blocks, `$` text) to mdast columns, as remark-parse with remark-math 6 does.
 * @param singleDollarTextMath Allow `$x$` text math (remark-math's `singleDollarTextMath`); pass true for
 *   remark-math's default.
 */
export declare function fromMarkdown(value: string, singleDollarTextMath?: boolean): MdastColumns
/**
 * Markdown with math to hast columns: remark-parse, remark-math and remark-rehype; math becomes the
 * `math-inline` and `math-display` elements rehype-katex reads.
 * @param allowDangerousHtml Keep raw HTML as `raw` nodes; default false.
 */
export declare function markdownToHast(value: string, allowDangerousHtml?: boolean): HastColumns
